// src/components/CommentComponent.jsx
import React from 'react'

import Comment, { CommentAction, CommentAuthor, CommentEdited, CommentTime } from '@atlaskit/comment';

function CommentComponent() {
  return React.createElement(
    "div",
    null,
    React.createElement(Comment, {
      author: React.createElement(
        CommentAuthor,
        null,
        "John Smith"
      ),
      type: "author",
      edited: React.createElement(
        CommentEdited,
        null,
        "Edited"
      ),
      restrictedTo: "Restricted to Admins Only",
      time: React.createElement(
        CommentTime,
        null,
        "30 August, 2016"
      ),
      content: React.createElement(
        "p",
        null,
        "Content goes here. This can include ",
        React.createElement(
          "a",
          { href: "/link" },
          "links"
        ),
        " and other content."
      ),
      actions: [React.createElement(
        CommentAction,
        null,
        "Reply"
      ), React.createElement(
        CommentAction,
        null,
        "Edit"
      ), React.createElement(
        CommentAction,
        null,
        "Like"
      )]
    })
  );
}

export default CommentComponent;

// src/components/CommentComponent.vue
<template>
  <Comment :author="author" :type="type" :edited="edited" :content="content" :time="time" :actions="actions"></Comment>
</template>

<script>
  import React from 'react'
  import Comment, { CommentAction, CommentAuthor, CommentEdited, CommentTime } from '@atlaskit/comment'
  const e = React.createElement
  export default {
    data() {
      return {
        content: e('p', null, '<div>c</div>'),
        time: e(CommentTime, null, '30 August, 2020'),
        author: e(CommentAuthor, null, 'John Smith'),
        type: 'author',
        edited: e(CommentEdited, null, 'Edited'),
        actions: [
          e(CommentAction, null, 'Reply')
        ]
      }
    },
    components: {
      Comment,
      CommentAuthor,
      CommentAction,
      CommentTime,
      CommentEdited
    }

  }
</script>
